parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.bundle.serializer.strictinteger:
        class: App\Bundle\Serializer\StrictIntegerHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
